### ISSUE TITLE
Add logs when unable to create bundle temp directory

### ISSUE THREAD

**Issue by alexandre-duquette** [OpenIdentityPlatform/OpenICF#4]
**Is your feature request related to a problem? Please describe.**
When starting openICF, application first try to load bundles under connectors directory. For each one, it try to create a temp directory, see here
https://github.com/OpenIdentityPlatform/OpenICF-java-framework/blob/2a811c2cfddc0c9b5ae962def71a19828490b7bb/connector-framework-internal/src/main/java/org/identityconnectors/framework/impl/api/local/LocalConnectorInfoManagerImpl.java#L495

Problem is when running on Kubernetes on a read-only file system, application is not able to create temp directory and loop indefinitely without error message. It takes time to find why.
The solution is easy when you know what the problem is, juste make a writable volume and specify java.io.tmpdir.

**Describe the solution you'd like**
Add a log when not able to create temp directory

**Describe alternatives you've considered**
No alternative solutions

**Additional context**

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenICF/releases/tag/1.6.0
